import {useState,useMemo} from 'react';import Card from './Card';
export default function SensorHistory({rows}){const [q,setQ]=useState('');const [d,setD]=useState('');const [st,setSt]=useState('ALL');const [pg,setPg]=useState(0);const PER=10;
 const f=useMemo(()=>[...rows].reverse().filter(r=>(!d||new Date(r.created_at).toLocaleDateString('en-CA')===d)&&(st==='ALL'||r.water_level_status===st||r.water_quality_status===st)&&(!q||JSON.stringify(r).toLowerCase().includes(q.toLowerCase()))),[rows,q,d,st]);
 const pages=Math.max(1,Math.ceil(f.length/PER)),inp='rounded-xl px-3 py-2 bg-white/70 dark:bg-white/10 text-sm outline-none focus:ring-2 ring-sky-400';
 return(<Card title="Sensor history"><div className="flex flex-wrap gap-2 mb-3"><input className={inp} placeholder="Search" value={q} onChange={e=>{setQ(e.target.value);setPg(0)}}/><input type="date" className={inp} value={d} onChange={e=>{setD(e.target.value);setPg(0)}}/>
 <select className={inp} value={st} onChange={e=>{setSt(e.target.value);setPg(0)}}>{['ALL','HIGH','MEDIUM','LOW','EMPTY','CLEAR','SLIGHTLY TURBID','TURBID'].map(x=><option key={x}>{x}</option>)}</select></div>
 <div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead className="opacity-60"><tr>{['Date','Time','Water level','Turbidity','Water quality','ESP32'].map(h=><th key={h} className="py-2 pr-4">{h}</th>)}</tr></thead>
 <tbody>{f.slice(pg*PER,pg*PER+PER).map(r=>{const t=new Date(r.created_at);return(<tr key={r.id} className="border-t border-slate-300/30"><td className="py-2 pr-4">{t.toLocaleDateString()}</td><td className="pr-4">{t.toLocaleTimeString()}</td><td className="pr-4">{r.water_level_status}{r.water_level_percentage!=null&&` (${Math.round(r.water_level_percentage)}%)`}</td><td className="pr-4">{r.turbidity_value}</td><td className="pr-4">{r.water_quality_status}</td><td>{r.esp32_status}</td></tr>)})}</tbody></table></div>
 <div className="flex items-center gap-3 mt-3 text-sm"><button disabled={pg===0} onClick={()=>setPg(pg-1)} className="px-3 py-1 rounded-lg bg-sky-500 text-white disabled:opacity-40">Prev</button>Page {pg+1} / {pages}<button disabled={pg+1>=pages} onClick={()=>setPg(pg+1)} className="px-3 py-1 rounded-lg bg-sky-500 text-white disabled:opacity-40">Next</button></div></Card>)}
